### PR TITLE
Add export-ignore entries to .gitattributes

### PR DESCRIPTION
**Pull request by VincentLanglet**
Hi @Ocramius,

Seems like there is no `export-ignore` directive in this repo.
I tried to add some.

### CODE REVIEW

**Review by fredden — COMMENTED** [review]
We should probably also add `composer.lock` to this list.

**Comment by VincentLanglet** [comment]
> We should probably also add `composer.lock` to this list.

Done

**Comment by Ocramius** [comment]
The simulated merges are really messing with CI here @_@ 

I think the patch is fine, just wondering about its build status: could you rebase on `4.10.x`, please?

**Comment by Ocramius** [comment]
Never mind, saw that #512 fixed this already.

Merging here - will fix-up if something breaks.

**Comment by Ocramius** [comment]
Thanks @VincentLanglet!

**Pull request merged**
