### PR TITLE
Adding *number* of unknown symbols above output table

### PR DESCRIPTION
**Pull request by ThomasLandauer**
Add number of errors above output table

### CODE REVIEW

**Review by Ocramius — APPROVED** [review]
LGTM

**Comment by Ocramius** [comment]
Tests require adjustments, but overall the improvement seems valid 👍

**Comment by Ocramius** [comment]
@ThomasLandauer could you adjust commit messages and issue description/title to explain what is being done, so that it comes out in the changelog in the end? :D

**Comment by ThomasLandauer** [comment]
Do you mean the commit messages at https://github.com/maglnet/ComposerRequireChecker/pull/212/commits ("Update CheckCommand.php", "Update BinaryTest.php", ...)? => Sorry, don't know how to change them :-(

But at least I managed to change the title :-)

**Comment by Ocramius** [comment]
@ThomasLandauer in your local environment, you can `git rebase -i master`, and then rename single commits :)

**Comment by ThomasLandauer** [comment]
Sorry, I've done everything on github.com - no local environment :-(

**Comment by Ocramius** [comment]
Figured (by the default commit messages) - I'll get the adjustments done when merging :+1:

**Comment by Ocramius** [comment]
Rebased and manually merged via de65f9af9476a0531162f8f18f2f229fa948eadd, thanks @ThomasLandauer!

**Pull request closed without merging**
