### PR TITLE
Adds default extensions

### PR DESCRIPTION
**Pull request by heiglandreas**
This commit adds the first additional extensions that should be
available by default

Those will be the ones mentioned in
http://php.net/manual/en/extensions.membership.php

This addresses #3

### CODE REVIEW

**Comment by maglnet** [comment]
I was just looking at this, too. :)

IMHO this list will do it:

```php
["Core", "date", "filter", "hash", "SPL", "Reflection", "session", "standard", "tokenizer", "Phar"]
```

All other extensions are listed in "bundled" or "external" Section but could be disabled with the `--disable-all` switch at compile time.

**Comment by maglnet** [comment]
Ok, I just compiled php7RC8 with `--disable-all` and it gives the following output:
```sh
./php -r "var_dump(get_loaded_extensions());"
array(6) {
  [0]=>
  string(4) "Core"
  [1]=>
  string(4) "date"
  [2]=>
  string(4) "pcre"
  [3]=>
  string(10) "Reflection"
  [4]=>
  string(3) "SPL"
  [5]=>
  string(8) "standard"
}
```

So, should this be the default?
What do you think, @heiglandreas ?

**Comment by heiglandreas** [comment]
Sounds reasonable. That's the absolute minimum you have to have to run PHP. 

The question is, whether we can somehow give the user a recommendation to add ext-this or ext-that depending on the found unincluded nodes.

**Comment by maglnet** [comment]
OK, so I think the list above should be the default.

Suggesting an extension depending on the found symbol could be easily done with the reflection API, if the matching extension is already loaded within the running PHP process.

But how, if the extension isn't loaded? Then we would need a pre generated list of symbols for each extension, this sounds possible for "default" extensions like MySQL etc, but way too hard for all extensions.

Am 2. Dezember 2015 23:48:28 MEZ, schrieb Andreas Heigl <notifications@github.com>:
>Sounds reasonable. That's the absolute minimum you have to have to run
>PHP. 
>
>The question is, whether we can somehow give the user a recommendation
>to add ext-this or ext-that depending on the found unincluded nodes. 
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/maglnet/ComposerRequireChecker/pull/6#issuecomment-161458524

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by heiglandreas** [comment]
The pre-generated list could be rendered out of the source-code of PHP I'm sure. 

The main question is, whether a user should get a recommendation like "You should think of adding ext-xyz to your require-section" or just the plain "we found function ABC and it's not in a default PHP". But that'S a different issue in my eyes.

**Comment by maglnet** [comment]
So, this is not WIP anymore?

**Comment by heiglandreas** [comment]
Spotting **every** detail! :wink:

**Comment by maglnet** [comment]
Shame on me ;) Just wanted to be sure i don't ruin your workflow. 
Thanks for spotting this.

**Pull request merged**
