### PR TITLE
Add `random` to core extensions

### PR DESCRIPTION
**Pull request by MidnightDesign**

### CODE REVIEW

**Comment by Ocramius** [comment]
As the test results show, the newly added detail requires a verification :)

**Comment by MidnightDesign** [comment]
> As the test results show, the newly added detail requires a verification :)

I'm on it, but I don't know if it will be that easy because PHP <8.2 doesn't know about the extension.

**Comment by Ocramius** [comment]
Yeh, will be tricky, especially considering mutation tests run on PHP 8.1 :thinking:

**Comment by MidnightDesign** [comment]
@Ocramius Should I run the mutation tests on 8.2 as well? I'm not sure if that can make any difference, but they're already running on 8.0 and 8.1.

**Comment by MidnightDesign** [comment]
Most of the new surviving mutants are probably coming from the Infection upgrade.

The only "real" new one is

```
--- Original
+++ New
@@ @@
         $definedSymbols = [];
         foreach ($extensionNames as $extensionName) {
             $extensionName = self::ALTERNATIVES[$extensionName] ?? $extensionName;
-            if ($extensionName === 'random' && PHP_VERSION_ID < 80200) {
+            if ($extensionName === 'random' && PHP_VERSION_ID <= 80200) {
                 continue;
             }
             try {
```

but I'm not sure how to kill that one. Should I just lower the minimum covered MSI?

**Comment by Ocramius** [comment]
Could you try with an inline suppression?

See https://github.com/Roave/BetterReflection/blob/01bfd42c3ce88f378edb4e1a7b063160c3359d5f/src/Util/FileHelper.php#L29

**Comment by MidnightDesign** [comment]
Done. Another option would be to just use `version_compare()` instead. I can't imagine a mutation for that.

**Comment by Ocramius** [comment]
Had to rollback to `phpunit/php-code-coverage:9.2.17`, since newer versions are foobar'd.

Ref: https://github.com/sebastianbergmann/php-code-coverage/pull/964

**Comment by Ocramius** [comment]
Hmm, score still went down - perhaps we should just revert all `composer.lock` and `composer.json` changes for now?

**Comment by MidnightDesign** [comment]
Some of the locked dependencies don't allow 8.2, that's why I upgraded them:

```
  Problem 1
    - ocramius/package-versions is locked to version 2.4.0 and an update of this package was not requested.
    - ocramius/package-versions 2.4.0 requires php ~8.0.0 || ~8.1.0 -> your php version (8.2.0) does not satisfy that requirement.
  Problem 2
    - phpspec/prophecy is locked to version 1.14.0 and an update of this package was not requested.
    - phpspec/prophecy 1.14.0 requires php ^7.2 || ~8.0, <8.2 -> your php version (8.2.0) does not satisfy that requirement.
  Problem 3
    - roave/infection-static-analysis-plugin is locked to version 1.13.x-dev and an update of this package was not requested.
    - roave/infection-static-analysis-plugin 1.13.x-dev requires php ~7.4.7|~8.0.0|~8.1.0 -> your php version (8.2.0) does not satisfy that requirement.
  Problem 4
    - ocramius/package-versions 2.4.0 requires php ~8.0.0 || ~8.1.0 -> your php version (8.2.0) does not satisfy that requirement.
    - vimeo/psalm v4.15.0 requires composer/package-versions-deprecated ^1.8.0 -> satisfiable by ocramius/package-versions[2.4.0].
    - vimeo/psalm is locked to version v4.15.0 and an update of this package was not requested.
```

**Comment by MidnightDesign** [comment]
Yay, seems like my last commit did the trick.

**Review by Ocramius — APPROVED** [review]
Excellent, thanks @MidnightDesign!

**Pull request merged**
