### PR TITLE
use a non-emulative Lexer for PhpParser

### LINKED ISSUE #196: Syntax error, unexpected T_MATCH
We encounter some strange behavior lately. On some projects/libraries, the checker returns the following error:

```
$ vendor/bin/composer-require-checker
ComposerRequireChecker 2.1.0@0c66698d487fcb5c66cf07108e2180c818fb2e72

In ParserAbstract.php line 315:

  Syntax error, unexpected T_MATCH on line 15


check [--config-file CONFIG-FILE] [--ignore-parse-errors] [--] [<composer-json>]
```

It seems to be somehow related to PHPunit when it is installed as non-dev dependency.
Psalm also had a similar problem but fixed it already: https://github.com/vimeo/psalm/issues/3901

The error disappears when I remove the `extends Match` from `\PHPUnit\Framework\MockObject\Builder\ParametersMatch` lins 15.

Anyone has a clue what's going on there?

### PR DESCRIPTION
**Pull request by rieschl**
so the  `Parser` uses the running PHP version.

fixes #196

### CODE REVIEW

**Review by Ocramius — CHANGES_REQUESTED** [review]
Can we add a test case, so that we can prevent regressions on this front?

**Comment by rieschl** [comment]
> Can we add a test case, so that we can prevent regressions on this front?

Hm yes I looked into it before submitting the PR but I couldn't think of an appropriate test setup.
`\ComposerRequireCheckerTest\ASTLocator\LocateASTFromFilesTest` already uses the non-emulative Lexer. I didn't notice it until I wrote a test that should fail but didn't 😉 

So if you can think of a test case, I'd be happy to try that if I can.

**Review by Ocramius — APPROVED** [review]
Oh, excellent! Also excellent work on the test \o/

**Comment by rieschl** [comment]
> Oh, excellent! Also excellent work on the test \o/

thanks! that means a lot to me, coming from you 🙃

I didn't run the test on php8, though.

**Pull request merged**
