### PR TITLE
Test on PHP 7.4

### PR DESCRIPTION
**Pull request by Lctrs**

### CODE REVIEW

**Comment by Ocramius** [comment]
Travis doesn't seem to yet have stable 7.4 pre-installed

**Comment by SignpostMarv** [comment]
should be snapshot for now?
```yaml
  - 7.4snapshot 
```

**Comment by kubawerlos** [comment]
`7.4` is working since yesterday on Travis

**Comment by Lctrs** [comment]
@Ocramius should be good.

**Pull request merged**
