### PR TITLE
Upgrade nikic/php-parser to 3.0 to get PHP 7.1 support

### PR DESCRIPTION
**Pull request by MidnightDesign**

### CODE REVIEW

**Comment by Ocramius** [comment]
@MidnightDesign can you look into the failure? `master` seemed green, so there's something borked in the dependency upgrade...

**Comment by MidnightDesign** [comment]
I don't really get what's going on here. It doesn't fail on the tests but when running the checker on itself. And `$type` is defined in the PhpParser copy that's installed on my machine when I run `composer install`. (I'm on Windows right now; PHP 7.1)

**Comment by Ocramius** [comment]
Probably worth running with `-vvv` to see a full trace

**Comment by MidnightDesign** [comment]
Huh? On Travis?

**Comment by Ocramius** [comment]
Yes, just adding `-vvv` to the command should do the trick

**Comment by Ocramius** [comment]
As per https://travis-ci.org/maglnet/ComposerRequireChecker/jobs/193685961#L257-L271, the failure is on the CLI command, not on the composer install

**Comment by MidnightDesign** [comment]
Got it. It's the `"minimum-stability": "dev"` setting, I think.

**Comment by Ocramius** [comment]
I got it locally too:

```
∙ ./bin/composer-require-checker                                                                                                                                                           3:34  ocramius@Marcos-MBP
ComposerRequireChecker 0.1.2-3-ge721f5c
PHP Notice:  Undefined property: PhpParser\Node\Stmt\Catch_::$type in /Users/ocramius/Documents/Projects/ComposerRequireChecker/src/ComposerRequireChecker/NodeVisitor/UsedSymbolCollector.php on line 93
PHP Stack trace:
PHP   1. {main}() /Users/ocramius/Documents/Projects/ComposerRequireChecker/bin/composer-require-checker:0
PHP   2. include() /Users/ocramius/Documents/Projects/ComposerRequireChecker/bin/composer-require-checker:3
PHP   3. Symfony\Component\Console\Application->run() /Users/ocramius/Documents/Projects/ComposerRequireChecker/bin/composer-require-checker.php:32
PHP   4. Symfony\Component\Console\Application->doRun() /Users/ocramius/Documents/Projects/ComposerRequireChecker/vendor/symfony/console/Application.php:121
PHP   5. Symfony\Component\Console\Application->doRunCommand() /Users/ocramius/Documents/Projects/ComposerRequireChecker/vendor/symfony/console/Application.php:190
PHP   6. Symfony\Component\Console\Command\Command->run() /Users/ocramius/Documents/Projects/ComposerRequireChecker/vendor/symfony/console/Application.php:838
PHP   7. ComposerRequireChecker\Cli\CheckCommand->execute() /Users/ocramius/Documents/Projects/ComposerRequireChecker/vendor/symfony/console/Command/Command.php:262
PHP   8. ComposerRequireChecker\UsedSymbolsLocator\LocateUsedSymbolsFromASTRoots->__invoke() /Users/ocramius/Documents/Projects/ComposerRequireChecker/src/ComposerRequireChecker/Cli/CheckCommand.php:79
PHP   9. PhpParser\NodeTraverser->traverse() /Users/ocramius/Documents/Projects/ComposerRequireChecker/src/ComposerRequireChecker/UsedSymbolsLocator/LocateUsedSymbolsFromASTRoots.php:29
PHP  10. PhpParser\NodeTraverser->traverseArray() /Users/ocramius/Documents/Projects/ComposerRequireChecker/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:72
PHP  11. PhpParser\NodeTraverser->traverseNode() /Users/ocramius/Documents/Projects/ComposerRequireChecker/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:139
PHP  12. PhpParser\NodeTraverser->traverseArray() /Users/ocramius/Documents/Projects/ComposerRequireChecker/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:88
PHP  13. PhpParser\NodeTraverser->traverseNode() /Users/ocramius/Documents/Projects/ComposerRequireChecker/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:139
PHP  14. PhpParser\NodeTraverser->traverseArray() /Users/ocramius/Documents/Projects/ComposerRequireChecker/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:88
PHP  15. PhpParser\NodeTraverser->traverseNode() /Users/ocramius/Documents/Projects/ComposerRequireChecker/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:139
PHP  16. PhpParser\NodeTraverser->traverseArray() /Users/ocramius/Documents/Projects/ComposerRequireChecker/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:88
PHP  17. PhpParser\NodeTraverser->traverseNode() /Users/ocramius/Documents/Projects/ComposerRequireChecker/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:139
PHP  18. PhpParser\NodeTraverser->traverseArray() /Users/ocramius/Documents/Projects/ComposerRequireChecker/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:88
PHP  19. PhpParser\NodeTraverser->traverseNode() /Users/ocramius/Documents/Projects/ComposerRequireChecker/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:139
PHP  20. PhpParser\NodeTraverser->traverseArray() /Users/ocramius/Documents/Projects/ComposerRequireChecker/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:88
PHP  21. ComposerRequireChecker\NodeVisitor\UsedSymbolCollector->enterNode() /Users/ocramius/Documents/Projects/ComposerRequireChecker/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:130
PHP  22. ComposerRequireChecker\NodeVisitor\UsedSymbolCollector->recordCatchUsage() /Users/ocramius/Documents/Projects/ComposerRequireChecker/src/ComposerRequireChecker/NodeVisitor/UsedSymbolCollector.php:45

Notice: Undefined property: PhpParser\Node\Stmt\Catch_::$type in /Users/ocramius/Documents/Projects/ComposerRequireChecker/src/ComposerRequireChecker/NodeVisitor/UsedSymbolCollector.php on line 93

Call Stack:
    0.0001     363328   1. {main}() /Users/ocramius/Documents/Projects/ComposerRequireChecker/bin/composer-require-checker:0
    0.0003     368200   2. include('/Users/ocramius/Documents/Projects/ComposerRequireChecker/bin/composer-require-checker.php') /Users/ocramius/Documents/Projects/ComposerRequireChecker/bin/composer-require-checker:3
    0.0152    1259184   3. Symfony\Component\Console\Application->run() /Users/ocramius/Documents/Projects/ComposerRequireChecker/bin/composer-require-checker.php:32
    0.0241    1504560   4. Symfony\Component\Console\Application->doRun() /Users/ocramius/Documents/Projects/ComposerRequireChecker/vendor/symfony/console/Application.php:121
    0.0244    1527976   5. Symfony\Component\Console\Application->doRunCommand() /Users/ocramius/Documents/Projects/ComposerRequireChecker/vendor/symfony/console/Application.php:190
    0.0245    1527976   6. Symfony\Component\Console\Command\Command->run() /Users/ocramius/Documents/Projects/ComposerRequireChecker/vendor/symfony/console/Application.php:838
    0.0247    1529680   7. ComposerRequireChecker\Cli\CheckCommand->execute() /Users/ocramius/Documents/Projects/ComposerRequireChecker/vendor/symfony/console/Command/Command.php:262
    5.7449    6064808   8. ComposerRequireChecker\UsedSymbolsLocator\LocateUsedSymbolsFromASTRoots->__invoke() /Users/ocramius/Documents/Projects/ComposerRequireChecker/src/ComposerRequireChecker/Cli/CheckCommand.php:79
    5.7890    5409576   9. PhpParser\NodeTraverser->traverse() /Users/ocramius/Documents/Projects/ComposerRequireChecker/src/ComposerRequireChecker/UsedSymbolsLocator/LocateUsedSymbolsFromASTRoots.php:29
    5.7891    5394064  10. PhpParser\NodeTraverser->traverseArray() /Users/ocramius/Documents/Projects/ComposerRequireChecker/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:72
    5.7891    5394488  11. PhpParser\NodeTraverser->traverseNode() /Users/ocramius/Documents/Projects/ComposerRequireChecker/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:139
    5.7891    5394584  12. PhpParser\NodeTraverser->traverseArray() /Users/ocramius/Documents/Projects/ComposerRequireChecker/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:88
    5.7892    5396520  13. PhpParser\NodeTraverser->traverseNode() /Users/ocramius/Documents/Projects/ComposerRequireChecker/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:139
    5.7892    5396640  14. PhpParser\NodeTraverser->traverseArray() /Users/ocramius/Documents/Projects/ComposerRequireChecker/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:88
    5.7892    5397440  15. PhpParser\NodeTraverser->traverseNode() /Users/ocramius/Documents/Projects/ComposerRequireChecker/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:139
    5.7893    5398104  16. PhpParser\NodeTraverser->traverseArray() /Users/ocramius/Documents/Projects/ComposerRequireChecker/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:88
    5.7893    5398328  17. PhpParser\NodeTraverser->traverseNode() /Users/ocramius/Documents/Projects/ComposerRequireChecker/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:139
    5.7894    5398496  18. PhpParser\NodeTraverser->traverseArray() /Users/ocramius/Documents/Projects/ComposerRequireChecker/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:88
    5.7894    5398920  19. PhpParser\NodeTraverser->traverseNode() /Users/ocramius/Documents/Projects/ComposerRequireChecker/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:139
    5.7900    5403592  20. PhpParser\NodeTraverser->traverseArray() /Users/ocramius/Documents/Projects/ComposerRequireChecker/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:88
    5.7901    5404440  21. ComposerRequireChecker\NodeVisitor\UsedSymbolCollector->enterNode() /Users/ocramius/Documents/Projects/ComposerRequireChecker/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:130
    5.7901    5404440  22. ComposerRequireChecker\NodeVisitor\UsedSymbolCollector->recordCatchUsage() /Users/ocramius/Documents/Projects/ComposerRequireChecker/src/ComposerRequireChecker/NodeVisitor/UsedSymbolCollector.php:45



  [Symfony\Component\Debug\Exception\FatalThrowableError]
  Type error: Argument 1 passed to ComposerRequireChecker\NodeVisitor\UsedSymbolCollector::recordUsageOf() must be an instance of PhpParser\Node\Name, null given, called in /Users/ocramius/Documents/Projects/Co
  mposerRequireChecker/src/ComposerRequireChecker/NodeVisitor/UsedSymbolCollector.php on line 93


check [--config-file CONFIG-FILE] [--] [<composer-json>]
```

**Comment by Ocramius** [comment]
The problem is probably due to a `catch (Foo | Bar) {`, since the AST for the `catch ()` syntax changed as per PHP 7.1

**Comment by MidnightDesign** [comment]
I can't reproduce the problem on this machine right now. Even tried it Bash on Windows. I'll try it on my Linux box on monday. If you find a fix until then just let me know and I'll give it a try.

**Comment by maglnet** [comment]
Hi, it seems your local version of `nikic/php-parser` isn't up to date.

`PhpParser/Node/Stmt/Catch_::$type` doesn't exist anymore, it's now an array and is called `$types`:
https://github.com/nikic/PHP-Parser/blob/cb5dd289856c45266dcf5de153b2d43019001404/lib/PhpParser/Node/Stmt/Catch_.php#L11

If you change the following line to iterate over `$node->types` it should be fixed.
https://github.com/maglnet/ComposerRequireChecker/blob/3c4a65252f546e2920b7e929516874e3a6721148/src/ComposerRequireChecker/NodeVisitor/UsedSymbolCollector.php#L93

**Comment by Ocramius** [comment]
0ec61e4 shouldn't be there - rebase instead :-\

**Comment by MidnightDesign** [comment]
Damn it, sorry. I'm a Git dummmy. Can I revert this somehow?

**Comment by Ocramius** [comment]
@MidnightDesign if you never did it before, leave it: I'm doing it on merge :-)

**Comment by Ocramius** [comment]
Manually rebased and merged 👍

**Pull request closed without merging**
