### PR TITLE
update php-parser to 4.0

### LINKED ISSUE #69: Upgrade to PHP Parser 4.0
PHP Parser 4.0 was released back in February, would be nice to use it here. :blush:

### PR DESCRIPTION
**Pull request by maglnet**
this should fix #69

### CODE REVIEW

**Comment by Ocramius** [comment]
:ship:

**Comment by rieschl** [comment]
@Ocramius do you know when you can release a new tag with this changes? I have to use `dev-master` at the moment because it clashes with current `phpstan` and `infection` versions. Maybe `0.2.2` is easier before jumping to `1.0`/stable? Thanks!

**Comment by Ocramius** [comment]
@rieschl a patch release is out of question, because dependency bumps can prevent upgrades downstream.

You'd either get a minor or the major release.

@maglnet I don't think there's anything blocking a `1.0.0` release (and we move to new major versions for further breakages, if needed). Would you agree if I tagged one?

**Comment by rieschl** [comment]
ah sorry, my mistake. I'm okay with anything, as long as it's tagged ;)
Thanks!

**Comment by maglnet** [comment]
@Ocramius I'm fine with a `1.0.0` release.
I'm going to change your review marks of #77 tonight, and also tag a new minor or major then, depending if you release earlier :-)

**Comment by Ocramius** [comment]
@maglnet won't get to it, but I strongly endorse `1.0.0`, since the tool is generally usable anyway :+1:

**Comment by maglnet** [comment]
@Ocramius yes, I'll release `THE version` later this day 👍

**Comment by maglnet** [comment]
@rieschl tagged 1.0.0 a minute ago :-) feel free to use/test and give feedback

**Comment by rieschl** [comment]
Thanks! I've been using `dev-master` for a while now and everything works as expected.
The only thing I noticed was that if a used package doesn't specify a `php` version in the `require` section, the update checker complains of missing PHP core libraries (`SPL` and stuff). If the package contains a `composer.lock` it doesn't work correctly for symbols of that package. But I haven't tested if it's a new issue or already existing in `0.2.1`

**Pull request merged**
