### PR TITLE
Enhancement: Update phpstan/phpstan

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] updates `phpstan/phpstan`

### CODE REVIEW

**Comment by Ocramius** [comment]
Hmm, I think we should set up @dependabot to get these done. Can you check that, @maglnet?

**Comment by maglnet** [comment]
Yes, I'll have a look at this in the next days.

**Comment by localheinz** [comment]
@maglnet 

Here's an example configuration file: https://github.com/localheinz/php-library-template/blob/master/.dependabot/config.yml.

**Comment by localheinz** [comment]
Thank you, @Ocramius!

**Pull request merged**
