### PR TITLE
Whitelist `object` (introduced in PHP 7.2)

### PR DESCRIPTION
**Pull request by weirdan**

### CODE REVIEW

**Comment by weirdan** [comment]
@maglnet done.

**Comment by Ocramius** [comment]
Tests please :-)

**Comment by weirdan** [comment]
Covered by `OptionsTest::testOptionsFileRepresentsDefaults()` I suppose. Or is there some other kind of test you'd like to see here, @Ocramius ?

**Comment by Ocramius** [comment]
@weirdan ah, I see. I think that's probably implemented incorrectly then, but that's for a separate issue. :+1:

**Comment by Ocramius** [comment]
@maglnet to clarify, the AST already tells us if some of these are "special" symbols. `iterable`, `object`, `array` and such are not `ClassLike` nodes.

**Comment by maglnet** [comment]
@Ocramius it seems all these "specials" are only `string` types, no `Nodes`, but I don't feel like it's safe to ignore all of these symbols, is it?

**Comment by weirdan** [comment]
Is this good to merge then? @Ocramius, @maglnet

**Comment by Ocramius** [comment]
Yep.

**Comment by Ocramius** [comment]
@maglnet we should catch up on a weekend to discuss this project in person (you live at dangerous range ;-) )

**Comment by Ocramius** [comment]
Thanks @weirdan!

**Pull request merged**
