### PR TITLE
ext-Zend Opcache vs ext-zend-opcache in composer

### LINKED ISSUE #99: zend-opcache conflict
Hi. Thanks so much for ComposerRequireChecker. I spent the day with it on a medium sized project and it found quite a few things to fix. great tool!

One small problem:

if i specify
```json
require: {
        "ext-zend-opcache": "*",
}
```
in my composer.json then `composer update` works as expected but i get an error ` Extension zend-opcache does not exist` from require checker.

if i specify
```json
require: {
        "ext-Zend Opcache": "*",
}
```
in composer.json, then `composer update` fails with `The requested PHP extension ext-zend opcache should be required as ext-zend-opcache.` but require checker is happy

### PR DESCRIPTION
**Pull request by pavarnos**
resolves #99

### CODE REVIEW

**Comment by pavarnos** [comment]
hm. my patch is the wrong way around. it assumes the extension in composer.json needs mangling. but its our extension name that needs mangling so it matches with the one in composer.json.

I need to race off to work and will be busy for a few days. Probably best to abandon this patch: its just a one liner.

**Comment by Ocramius** [comment]
@pavarnos the "busy for a few days" applies to us all: please simply continue work here when/if you have a resolution path.

**Comment by pavarnos** [comment]
fair comment.
removed my earlier change, which was in the wrong place.
considered 2 alternatives for the new change
1. allowing the exception to occur if the package name didn't exist, then trying again after replacing '-' with ' ' in the name
2. a lookup table 

1 is more general but more complicated for what is probably only a single extension with this problem. 2 is much shorter, but a lot simpler / more obvious. So i went with that. Hope thats ok.

**Comment by maglnet** [comment]
Yes, seems like composer home directory changed, I'll have a look at it.

**Comment by Ocramius** [comment]
@pavarnos can you please rebase your branch on `master`, so we see if it passes all of the CI checks?

**Comment by maglnet** [comment]
@pavarnos #101 should have fixed the build, could you please rebase onto master?

**Comment by pavarnos** [comment]
done

**Comment by Ocramius** [comment]
Heya, please rebase, don't merge `master` into feature branches

**Comment by pavarnos** [comment]
apologies. first time i ever rebased. googled for it and found some instructions on github (that i can't seem to find again). can you paste a link with the right way to do it (and how to undo the mess i already made)? sorry.

**Comment by pavarnos** [comment]
done

**Pull request merged**
