### PR TITLE
Bump psalm to v4.15

### PR DESCRIPTION
**Pull request by simPod**
#338

### CODE REVIEW

**Review by Ocramius — CHANGES_REQUESTED** [review]
Interesting: the bump to `4.15` means that some mutants now escape. Perhaps regression (or change) in type inference leading to more mutations?

/cc @dkreuer (just for interest)

**Comment by simPod** [comment]
I noticed the same in few other repos. Should I improve tests to cover those?

**Comment by dkreuer** [comment]
I don't think that there are more mutations now - at least the numbers are kind of what I'd expect.

But I'm a bit worried because a lot mutants now take even more time (and are therefore handled as escaped).

I have planned to work on moving integration tests into excluded group and on the other hand write more unit tests. That should fix the pipeline issues for this PR as well. But every help in that effort would be appreciated I guess.

**Comment by simPod** [comment]
So what I do in order to ship psalm 4.15 now? Just adjust MSI %?

**Review by Ocramius — APPROVED** [review]
See? A rebase sufficed :D 

LGTM :+1:

**Comment by simPod** [comment]
🤦🏾‍♀️ 😄 🙃

**Pull request merged**
