### PR TITLE
Support `mixed` type

### LINKED ISSUE #250: Tool complains about "mixed"
ComposerRequireChecker 3.1.0@b3cd6d30e2335997c5eabb19e3f01d699bc06caa

```
The following 1 unknown symbols were found:
+----------------+--------------------+
| Unknown Symbol | Guessed Dependency |
+----------------+--------------------+
| mixed          |                    |
+----------------+--------------------+
```
Error: Process completed with exit code 1.

### PR DESCRIPTION
**Pull request by OskarStark**
Closes #250

### CODE REVIEW

**Review by Ocramius — APPROVED** [review]
LGTM :+1:

**Comment by Ocramius** [comment]
`testOptionsFileRepresentsDefaults` needs to be adjusted

**Review by DanielBadura — APPROVED** [review]

**Comment by OskarStark** [comment]
All 🟢

**Comment by Ocramius** [comment]
@OskarStark please squash and adjust commit messages though :sweat_smile:

**Comment by OskarStark** [comment]
I did this via UI 😄 ... Would it be able to squash via Github UI on your side?

**Comment by OskarStark** [comment]
Done

**Comment by Ocramius** [comment]
Thanks @OskarStark!

**Comment by OskarStark** [comment]
Thank you, I saw the commit is already released with 3.2.0.
Will the PHAR soon be available? @maglnet

**Comment by Ocramius** [comment]
That's not yet automated, so I cannot do that part from this end

**Comment by Ocramius** [comment]
> I did this via UI smile ...

BTW, it really is important to have good commit messages - consider it for the next time you use the web UI for committing :D

**Pull request merged**
